### ISSUE TITLE
MissingPluginException(No implementation found for method promptPermissions on channel wifi_flutter)

### ISSUE THREAD

**Issue by theBoilingPoint** [weplenish/flutter-plugins#14]
Hi, 

I have followed the instruction to install the plugin. When I was running the example code in my flutter project, the app bar was shown successfully. Then when I clicked on the button, nothing happened and this error showed in my terminal:

E/flutter (16286): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: MissingPluginException(No implementation found for method promptPermissions on channel wifi_flutter)
E/flutter (16286): #0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:157:7)
E/flutter (16286): <asynchronous suspension>
E/flutter (16286): #1      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (16286): #2      WifiFlutter.promptPermissions (package:wifi_flutter/wifi_flutter.dart:15:16)
E/flutter (16286): #3      _MyAppState.build.<anonymous closure> (package:prj/main.dart:59:53)
E/flutter (16286): #4      _InkResponseState._handleTap (package:flutter/src/material/ink_well.dart:993:19)
E/flutter (16286): #5      _InkResponseState.build.<anonymous closure> (package:flutter/src/material/ink_well.dart:1111:38)
E/flutter (16286): #6      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:183:24)
E/flutter (16286): #7      TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:598:11)
E/flutter (16286): #8      BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:287:5)
E/flutter (16286): #9      BaseTapGestureRecognizer.handlePrimaryPointer (package:flutter/src/gestures/tap.dart:222:7)
E/flutter (16286): #10     PrimaryPointerGestureRecognizer.handleEvent (package:flutter/src/gestures/recognizer.dart:476:9)
E/flutter (16286): #11     PointerRouter._dispatch (package:flutter/src/gestures/pointer_router.dart:77:12)
E/flutter (16286): #12     PointerRouter._dispatchEventToRoutes.<anonymous closure> (package:flutter/src/gestures/pointer_router.dart:122:9)
E/flutter (16286): #13     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (16286): #14     PointerRouter._dispatchEventToRoutes (package:flutter/src/gestures/pointer_router.dart:120:18)
E/flutter (16286): #15     PointerRouter.route (package:flutter/src/gestures/pointer_router.dart:106:7)
E/flutter (16286): #16     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:358:19)
E/flutter (16286): #17     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:338:22)
E/flutter (16286): #18     RendererBinding.dispatchEvent (package:flutter/src/rendering/binding.dart:267:11)
E/flutter (16286): #19     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:295:7)
E/flutter (16286): #20     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:240:7)
E/flutter (16286): #21     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:213:7)
E/flutter (16286): #22     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter (16286): #23     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter (16286): #24     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter (16286): #25     _invoke1 (dart:ui/hooks.dart:265:10)
E/flutter (16286): #26     _dispatchPointerDataPacket (dart:ui/hooks.dart:174:5)

**Comment by theBoilingPoint** [comment]
Solved by disconnecting and restart the app on the phone
